POST http://localhost:3001/api/persons
//POST https://fs-phonebook-15082022.herokuapp.com/api/persons
Content-Type: application/json

{
      "name": "Martin Fowler",
      "number": "+234 23-3345"
}
